### ISSUE TITLE
Audio issues when device throttles performance

### ISSUE THREAD

**Issue by kurtulusakyuz** [ia-me176c/device-asus-K013#34] opened 2017-08-12 08:37 UTC
When you play a media, the audio mixes. After a while playing the game starts to freeze, the sound is mixed.

**Comment by lambdadroid** [comment] 2017-08-12 09:12
What do you mean with "the audio mixes"? That doesn't make any sense.

**Comment by kurtulusakyuz** [comment] 2017-08-12 10:49
https://www.youtube.com/watch?v=c0Z_zb86chA&feature=youtu.be

**Comment by lambdadroid** [comment] 2017-08-12 11:43
I've heard something similar before when switching between headphones and speaker while audio was playing. Did you switch between speaker and headphones?

**Comment by kurtulusakyuz** [comment] 2017-08-12 11:57
No, I did not wear a headset.

**Comment by lambdadroid** [comment] 2017-08-12 13:01
Please test if stopping the video and then waiting for about 10 seconds before starting the video again fixes the issue. If that doesn't help try a restart. Do you frequently run into this problem?

**Comment by kurtulusakyuz** [comment] 2017-08-12 13:53
I wait 10 seconds. After a while it happens again. It's the same after you start it again. This process is heating up the tablet.

**Comment by lambdadroid** [comment] 2017-08-12 14:45
I can take a look at the log file if you can upload it (make sure it's taken when it's actually happening  with the sound). I regularly watch YouTube videos and that has never happened for me.

**Comment by kurtulusakyuz** [comment] 2017-08-12 15:00
https://gist.github.com/kurtulus145/ddf9ed7bae1eb9b5b486e799e54f4b72

**Comment by kurtulusakyuz** [comment] 2017-08-12 15:01
I think it's because of the sound drivers.

**Comment by lambdadroid** [comment] 2017-08-12 15:37
Well, that log is much more interesting! It looks like it's not directly an issue in the sound driver but rather an issue on the Android side. I noticed in your log that the thermal daemon is throttling your device performance because your tablet gets too hot.

Please try to turn off your tablet for like half an hour, let it cool down and then try again. Do you get the sound issues while it's still cool, or only when it's hot?

**Comment by kurtulusakyuz** [comment] 2017-08-12 17:57
The tablet was closed for 1 hour 30 minutes. I opened the tablet and entered YouTube. After 15 minutes on Youtube, it started to froze and the sound problem started. The same goes for games.

**Comment by lambdadroid** [comment] 2017-08-12 18:17
It's quite weird that your tablet gets hot so quickly. Did it get that hot on the ASUS system as well?

**Comment by kurtulusakyuz** [comment] 2017-08-12 19:36
The Asus system was not heating up immediately. Even if it got warm, it did not freeze on YouTube and games.

**Comment by lambdadroid** [comment] 2017-08-13 08:42
I believe the actual issue here is the massive heat generated by your tablet for some reason. Did you modify the performance profile in the battery settings? Maybe you have a lot of apps doing expensive background activity.

Something must be driving your CPU to maximum usage (and that can't be only YouTube) and this is the reason why you get audio problems. According to the log, the thermal monitor has problems throttling your device performance because it just heats up more and more.....

**Comment by kurtulusakyuz** [comment] 2017-08-13 09:01
Almost all applications have been erased. I got the mode performance from the battery settings. It was the same again.

**Comment by lambdadroid** [comment] 2017-08-13 09:08
I'm sorry, but I don't know what I should do with this issue. You can try doing a factory reset, and then keep all settings as-is and install only YouTube. Turn the tablet off until it's cool and then start it and start watching a few videos. The audio issues shouldn't happen.

**Comment by kurtulusakyuz** [comment] 2017-08-13 19:39
It's happening again.Was not this a problem when you were playing media?

**Comment by lambdadroid** [comment] 2017-08-14 07:10
No, I haven't had this problem yet. I believe it's happening because your tablet is getting so extremely hot. Have you had this problem while your tablet wasn't that warm?

**Comment by kurtulusakyuz** [comment] 2017-08-14 07:18
There is no problem when the tablet is cold. When it starts to warm up, the videos start to freeze.

**Comment by lambdadroid** [comment] 2017-08-14 07:20
Yeah, they freeze because the device is throttling the performance. The actual question is why your tablet gets hot so quickly.

**Comment by lambdadroid** [comment] 2017-08-14 10:00
OK, I tested playing a few games and some of them seem to be so extremely bad coded that they heat up the tablet extremely quickly, while others don't have that problem. However, the audio issues definitely happen when the tablet heats up, but I'm not sure if there is much I can do about it...

**Comment by kurtulusakyuz** [comment] 2017-08-14 11:56
The governor is set to powersave, although I can not do anything. I only surfed the internet (I did not do anything to force the device) but the temperatures are too high.
![screenshot_20170814-145307](https://user-images.githubusercontent.com/8530122/29270730-cbf46362-8100-11e7-9e51-b07d57925525.png)
![screenshot_20170814-145159](https://user-images.githubusercontent.com/8530122/29270731-cbfb0226-8100-11e7-8f7d-96e7a0f63eaa.png)

**Comment by lambdadroid** [comment] 2017-08-14 16:35
These temperatures are fine, it only starts throttling when `STR1`/`STR2` reach 55°C.

**Comment by lambdadroid** [comment] 2017-08-14 16:46
I'm going to close this issue. The cause of the audio problems is the performance throttling to keep the device temperature below the threshold. I've opened https://github.com/me176c-dev/device_asus_me176c/issues/36 to investigate ways to reduce the heat (and therefore the throttling) in the future, although I'm currently unsure if I will find a solution for this problem.

If this issue causes big problems for you I suggest that you switch back to the ASUS system. It will take a while to find a solution, and eventually I won't find a solution at all.

**Closed as completed by lambdadroid** 2017-08-14 16:46 UTC
Labels: status: confirmed
