### ISSUE TITLE
Weird sound issues on youtube

### ISSUE THREAD

**Issue by Ruben7173** [ia-me176c/device-asus-K013#11] opened 2017-07-08 11:28 UTC
Sometimes youtube has to be reloaded several times for sound to actually start playing on headphones

**Comment by lambdadroid** [comment] 2017-07-24 17:11
I cannot reproduce this. Are you using my app (the quick setting tile added by the "HeadphoneToggle" app included in the ROM)? I watched various YouTube videos for over an hour yesterday with headphones and had no sound issues at all, after switching to headphone mode using the quick settings tile. Sound played directly on the first try.

The only weird thing was that there was a quite annoying cracking noise when the sound started (and was muted before), which sounds a bit like some kind of power saving feature.

**Comment by lambdadroid** [comment] 2017-08-08 10:54
Closing, I don't think this is still present in the build I will release in the next few days. There is one thing to keep in mind though and that is #20. Make sure to plug in the headphones before playing any audio (best is to plug them in before starting YouTube or similar) otherwise audio will either freeze or sound really weird.

**Closed as completed by lambdadroid** 2017-08-08 10:54 UTC
Labels: type: bug, status: cannot reproduce
