### ISSUE TITLE
The system sometimes reboots randomly

### ISSUE THREAD

**Issue by RandomTypek** [ia-me176c/device-asus-K013#59] opened 2019-02-02 12:13 UTC
I can't really reproduce this, it doesn't happen often, but sometimes the screen freezes for 20+ seconds, then it goes black for like 10 seconds, and then the system reboots. I've also encountered a case where it just restarted SystemUI and the system kept working, but WiFi stopped working and I couldn't type anything, as the keyboard showing up caused it to freeze again (that was on a very early build though, probably the second one you've released). I wasn't able to get a log for this yet, sorry!

**Comment by lambdadroid** [comment] 2019-02-02 14:45
Thanks for the report! I understand that these kind of issues are annoying and hard to track down. Unfortunately, without a log and/or a way to reproduce it reliably on the latest build there is absolutely nothing I can do.

If you find a way to trigger that condition, or manage to get a related log dump, feel free to comment here. Until then I will close this issue.

**Closed as completed by lambdadroid** 2019-02-02 14:45 UTC

**Comment by RandomTypek** [comment] 2019-02-07 13:57
Here is a console-ramoops log taken right after a random reboot, not sure if this is related at all though, I don't know which logs are relevant in a situation like this.. I'll be trying to get a logcat right before the reboot if that's necessary

[console-ramoops.txt](https://github.com/me176c-dev/android_device_asus_K013/files/2841061/console-ramoops.txt)

**Comment by lambdadroid** [comment] 2019-02-08 00:37
> Here is a console-ramoops log taken right after a random reboot, not sure if this is related at all though, I don't know which logs are relevant in a situation like this.. I'll be trying to get a logcat right before the reboot if that's necessary
> 
> [console-ramoops.txt](https://github.com/me176c-dev/android_device_asus_K013/files/2841061/console-ramoops.txt)

That looks like a regular reboot.
